branch-defaults:
  master:
    environment: null
global:
  application_name: rails-beanstalk
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
